language: ruby
rvm:
  - "2.0.0"
  - "2.1.3"
  - '2.2.0'
before_install:
  - wget -c "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-x64-linux.tar.gz" && tar xvf ncbi-blast-2.2.30+-x64-linux.tar.gz && export PATH="./ncbi-blast-2.2.30+/bin:$PATH"
cache: bundler
sudo: false
script: bundle exec rake test
